### ISSUE TITLE
Color HEX code

### ISSUE THREAD

**Issue by tizionario** [MrBIMC/VintageChroma#1]
Why don't you add the HEX value too? It could be more useful than RGB or HSV

**Comment by MrBIMC** [comment]
Ok.

**Comment by MrBIMC** [comment]
I added this option in the last commit, though I did not yet push it to jcenter, so if you urgently need it right now, you gotta clone the repo and use the local copy. 

To define the indicator just add:
```
.indicatorMode(IndicatorMode.HEX) //HEX or DECIMAL; Note that ColorMode.HSV and IndicatorMode.HEX is a bad idea
```
...to your ChromaDialog.Builder();

**Comment by MrBIMC** [comment]
Release 1.1 pushed with this feature included.
