### ISSUE TITLE
Dialog buttons hidden on smaller devices (ColorMode.ARGB)

### ISSUE THREAD

**Issue by nicholasrout** [MrBIMC/VintageChroma#11]
Hi there,

I encountered an issue in my app where users with smaller devices were reporting they could not set a color, because the dialog buttons ('OK', 'Cancel') were not visible. This does not appear to be linked to Android version.

![screenshot_2016-05-24-10-55-55](https://cloud.githubusercontent.com/assets/12491712/15504379/f4cbd6be-21be-11e6-908b-e8679305778d.png)

I was using ColorMode.ARGB, and managed to show the buttons by switching to ColorMode.RGB. I suspect it is to do with the height of the dialog being greater than the height of the device.

**Comment by MrBIMC** [comment]
oh. Ok, I'll release fix that will make colorArea twice as smaller on ldpi devices.

**Comment by nicholasrout** [comment]
@MrBIMC you may need to consider mdpi and hdpi devices too. I saw it happen on a Galaxy S3 Mini and a Huawei Ascend Y300

**Comment by MrBIMC** [comment]
Done.

Also note that I changed how this thing works with prefs-v7(if you need it). Since 1.5 there's no more need to manually inject SupportFragmentManager into each preference-v7. Instead lib fallbacks to a plain AlertDialog which is a bit less flexible, but works better in that specific case.
