### ISSUE TITLE
Preference Screen

### ISSUE THREAD

**Issue by tellfa** [MrBIMC/VintageChroma#3]
Hi, thanks you for this library.
please add component for Preference Screen and write how to use that . thank you

**Comment by MrBIMC** [comment]
Already Made it, will push it later today/early tomorrow :D

**Comment by tellfa** [comment]
Thank man ;)

**Comment by MrBIMC** [comment]
Released!
Will publish it to bintray asap!

Checkout updated readme for more details: https://github.com/MrBIMC/VintageChroma/blob/master/README.md

https://github.com/MrBIMC/VintageChroma/releases/tag/1.2
