### ISSUE TITLE
Support for API levels below 14?

### ISSUE THREAD

**Issue by JoseGD** [MrBIMC/VintageChroma#4]
Any chance to bring support for API levels below the present mimimum?
I'm asking because I liked this simple color picker and I would love to integrate it in my projects that have minSDKVersion set to 8

**Comment by MrBIMC** [comment]
Well, I can easily support v11, but v11 will be a bit tricky. Anyway, I'll try.

**Comment by MrBIMC** [comment]
Actually, it went easier than expected. Will push update later today!

**Comment by JoseGD** [comment]
Great news! Thank you.
Now I realize that with API 8 I was really asking another thing, sorry... I'll open a new issue

**Comment by MrBIMC** [comment]
released v1.4 that supports API-7+
