### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by Pablode** [MrBIMC/VintageChroma#6]
Getting this build error: 
`Error :Execution failed for task ':app:processDebugManifest'. Manifest merger failed : Attribute application@label value=(@string/launcher_title) from AndroidManifest.xml:23:9-47
	is also present at [com.pavelsikun:vintage-chroma:1.4] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:21:5-104:19 to override.`

I suspect [this line](https://github.com/MrBIMC/VintageChroma/blob/08e7641917c632e695aa5ba8af9b99f742d1343d/library/src/main/AndroidManifest.xml#L6) in the library manifest to be the cause. A library should not need application tag attributes at all. Here are some example `AndroidManifest.xml` files from other libraries: [(1)](https://github.com/umano/AndroidSlidingUpPanel/blob/master/library/src/main/AndroidManifest.xml), [(2)](https://github.com/afollestad/material-dialogs/blob/master/core/src/main/AndroidManifest.xml), [(3)](https://github.com/amulyakhare/TextDrawable/blob/master/library/src/main/AndroidManifest.xml), [(4)](https://github.com/facebook/fresco/blob/master/fbcore/AndroidManifest.xml).

**Comment by MrBIMC** [comment]
Done. Will push new release soon with bunch of other bugfixes.
