### ISSUE TITLE
HSL fails for L = 0

### ISSUE THREAD

**Issue by cranphin** [MrBIMC/VintageChroma#7]
When setting L to 0 in HSL, the hue changes, and S has no effect.
 
This is a bug in the following code:
```
    float[] hsl2hsv(float[] hsl) {
        float a = hsl[0];
        float b = hsl[1];
        float c = hsl[2];

        b *= c < 0.5 ? c : 1 - c;
        return new float[] { a, 2 * b / (c + b), c + b };
    }
```
Adding some debug statements tells us this:
Inputs: H:230.0, S:1.0, L:0.0
Intermediate: B:0.0
Outputs: H:230.0, **S:NaN**, V:0.0

The problem is that the value for S, defined as: "2 * b / (c + b)", results in division by zero when b = 0, which happens when c(input L) is 0: "2* 0/ (0 + 0)".

Not sure how to fix, find a better algorithm on google? :)

**Comment by MrBIMC** [comment]
Ok, I solved this problem using a very simple hack: 
```
if (b == 0) b = 0.001f;
```

Sorta works. Also I noticed that indication of initial saturation was derped a bit(and thus fixed it too).
